rm -rf node_modules/.bin/json5
rm -rf node_modules/.bin/loose-envify
rm -rf node_modules/.bin/node-which
rm -rf node_modules/@babel/highlight/node_modules/
rm -rf node_modules/eslint-config-tencent/base-legacy.js
rm -rf node_modules/eslint-config-tencent/ts-legacy.js
rm -rf node_modules/@types/json5/
rm -rf node_modules/array.prototype.flatmap/
rm -rf node_modules/chalk/index.d.ts
rm -rf node_modules/chalk/node_modules/
rm -rf node_modules/chalk/source/
rm -rf node_modules/eslint-plugin-import/docs/rules/imports-first.md
rm -rf node_modules/eslint-plugin-react/lib/util/isFirstLetterCapitalized.js
rm -rf node_modules/eslint-plugin-vue/lib/configs/vue3-essential.js
rm -rf node_modules/eslint-plugin-vue/lib/configs/vue3-recommended.js
rm -rf node_modules/eslint-plugin-vue/lib/configs/vue3-strongly-recommended.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/block-tag-newline.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/comma-spacing.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/comma-style.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/custom-event-name-casing.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/dot-notation.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/experimental-script-setup-vars.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/func-call-spacing.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/html-comment-content-newline.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/html-comment-content-spacing.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/html-comment-indent.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-arrow-functions-in-watch.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-bare-strings-in-template.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-custom-modifiers-on-v-model.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-data-object-declaration.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-destroyed-lifecycle.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-dollar-listeners-api.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-dollar-scopedslots-api.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-events-api.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-filter.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-functional-template.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-html-element-is.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-inline-template.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-props-default-this.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-v-bind-sync.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-v-on-native-modifier.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-v-on-number-modifiers.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-deprecated-vue-config-keycodes.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-dupe-v-else-if.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-duplicate-attr-inheritance.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-empty-component-block.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-extra-parens.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-lifecycle-after-await.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-lone-template.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-multiple-objects-in-class.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-multiple-slot-args.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-multiple-template-root.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-mutating-props.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-potential-component-option-typo.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-ref-as-operand.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-restricted-component-options.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-restricted-static-attribute.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-restricted-v-bind.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-setup-props-destructure.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-sparse-arrays.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-template-target-blank.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-unregistered-components.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-unused-properties.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-useless-concat.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-useless-mustaches.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-useless-v-bind.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-v-for-template-key-on-child.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-v-for-template-key.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-v-model-argument.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/no-watch-after-await.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/object-curly-newline.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/object-property-newline.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/one-component-per-file.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/operator-linebreak.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/prefer-template.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/require-explicit-emits.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/require-slots-as-functions.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/require-toggle-inside-transition.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/return-in-emits-validator.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/space-in-parens.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/syntaxes/v-is.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/syntaxes/v-model-argument.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/syntaxes/v-model-custom-modifiers.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/template-curly-spacing.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/v-for-delimiter-style.js
rm -rf node_modules/eslint-plugin-vue/lib/rules/valid-v-is.js
rm -rf node_modules/eslint-plugin-vue/lib/utils/html-comments.js
rm -rf node_modules/eslint-plugin-vue/lib/utils/keycode-to-key.js
rm -rf node_modules/eslint-plugin-vue/lib/utils/vue-component-options.json
rm -rf node_modules/esrecurse/node_modules/
rm -rf node_modules/inquirer/lib/utils/incrementListIndex.js
rm -rf node_modules/is-core-module/
rm -rf node_modules/is-negative-zero/
rm -rf node_modules/json5/
rm -rf node_modules/jsx-ast-utils/lib/values/expressions/AssignmentExpression.js
rm -rf node_modules/jsx-ast-utils/lib/values/expressions/ChainExpression.js
rm -rf node_modules/jsx-ast-utils/lib/values/expressions/OptionalCallExpression.js
rm -rf node_modules/jsx-ast-utils/lib/values/expressions/SequenceExpression.js
rm -rf node_modules/jsx-ast-utils/lib/values/expressions/TSNonNullExpression.js
rm -rf node_modules/jsx-ast-utils/node_modules/
rm -rf node_modules/jsx-ast-utils/src/values/expressions/AssignmentExpression.js
rm -rf node_modules/jsx-ast-utils/src/values/expressions/ChainExpression.js
rm -rf node_modules/jsx-ast-utils/src/values/expressions/OptionalCallExpression.js
rm -rf node_modules/jsx-ast-utils/src/values/expressions/SequenceExpression.js
rm -rf node_modules/jsx-ast-utils/src/values/expressions/TSNonNullExpression.js
rm -rf node_modules/normalize-package-data/node_modules/
rm -rf node_modules/object.entries/.editorconfig
rm -rf node_modules/path-key/index.d.ts
rm -rf node_modules/rxjs/_esm2015/internal/innerSubscribe.js
rm -rf node_modules/rxjs/_esm2015/internal/innerSubscribe.js.map
rm -rf node_modules/rxjs/_esm5/internal/innerSubscribe.js
rm -rf node_modules/rxjs/_esm5/internal/innerSubscribe.js.map
rm -rf node_modules/rxjs/internal/innerSubscribe.d.ts
rm -rf node_modules/rxjs/internal/innerSubscribe.js
rm -rf node_modules/rxjs/internal/innerSubscribe.js.map
rm -rf node_modules/rxjs/src/internal/innerSubscribe.ts
rm -rf node_modules/semver/bin/semver.js
rm -rf node_modules/semver/classes/
rm -rf node_modules/semver/functions/
rm -rf node_modules/semver/index.js
rm -rf node_modules/semver/internal/
rm -rf node_modules/semver/preload.js
rm -rf node_modules/semver/ranges/
rm -rf node_modules/shebang-regex/index.d.ts
rm -rf node_modules/side-channel/node_modules/
rm -rf node_modules/table/node_modules/ansi-regex/
rm -rf node_modules/table/node_modules/strip-ansi/
rm -rf node_modules/tsconfig-paths/
rm -rf node_modules/uri-js/LICENSE
rm -rf node_modules/uri-js/dist/esnext/schemes/ws.d.ts
rm -rf node_modules/uri-js/dist/esnext/schemes/ws.js
rm -rf node_modules/uri-js/dist/esnext/schemes/ws.js.map
rm -rf node_modules/uri-js/dist/esnext/schemes/wss.d.ts
rm -rf node_modules/uri-js/dist/esnext/schemes/wss.js
rm -rf node_modules/uri-js/dist/esnext/schemes/wss.js.map
rm -rf node_modules/vue-eslint-parser/node_modules/espree/
rm -rf node_modules/which/bin/node-which
