FROM mirrors.tencent.com/codecc/base:latest
RUN pip3 install Werkzeug typed_ast requests MarkupSafe Jinja2 itsdangerous Flask_RESTful entrypoints ccsyspath aniso8601 -i http://mirrors.cloud.tencent.com/pypi/simple/ --trusted-host mirrors.cloud.tencent.com
RUN mkdir -p /usr/codecc/tool_scan
COPY sdk /usr/codecc/tool_scan/sdk/
COPY third_rules /usr/codecc/tool_scan/third_rules/
COPY tool /usr/codecc/tool_scan/tool
COPY third_rules/tencent.py /usr/codecc/tool_scan/tool/py2/pylint/checkers/
COPY third_rules/* /usr/codecc/tool_scan/tool/py3/pylint/checkers/
RUN chmod -R 755 /usr/codecc/tool_scan
WORKDIR /usr/codecc/tool_scan