FROM docker.io/bkci/codecc:latest
RUN pip3 install ijson -i http://mirrors.cloud.tencent.com/pypi/simple/ --trusted-host mirrors.cloud.tencent.com
RUN mkdir -p /usr/codecc/software
RUN mkdir -p /usr/codecc/tool_scan
COPY sdk /usr/codecc/tool_scan/sdk/
COPY tool /usr/codecc/tool_scan/tool/
RUN chmod -R 755 /usr/codecc/tool_scan
WORKDIR /usr/codecc/tool_scan
