FROM docker.io/bkci/codecc:latest
RUN mkdir -p /usr/codecc/software
COPY software/*.tar.gz /usr/codecc/software
WORKDIR /usr/codecc/software
RUN ls -l *.tar.gz
RUN md5sum mono-5.12.0.226.tar.gz
RUN md5sum mono-5.12.0.226-lib1.tar.gz
RUN md5sum mono-5.12.0.226-lib2.tar.gz
RUN md5sum mono-5.12.0.226-lib3.tar.gz
RUN md5sum mono-5.12.0.226-lib4.tar.gz
RUN md5sum mono-5.12.0.226-lib5.tar.gz
RUN md5sum mono-5.12.0.226-lib6.tar.gz
RUN tar zxvf mono-5.12.0.226.tar.gz
RUN tar zxvf mono-5.12.0.226-lib1.tar.gz
RUN tar zxvf mono-5.12.0.226-lib2.tar.gz
RUN tar zxvf mono-5.12.0.226-lib3.tar.gz
RUN tar zxvf mono-5.12.0.226-lib4.tar.gz
RUN tar zxvf mono-5.12.0.226-lib5.tar.gz
RUN tar zxvf mono-5.12.0.226-lib6.tar.gz
RUN rm -rf /usr/codecc/software/*.tar.gz
RUN chmod -R 755 /usr/codecc/software/mono-5.12.0.226
RUN ls -l /usr/codecc/software/mono-5.12.0.226
RUN ls -l /usr/codecc/software/mono-5.12.0.226/lib
ENV MONO_PATH=/usr/codecc/software/mono-5.12.0.226
ENV PATH="${MONO_PATH}/bin:${PATH}"
RUN mkdir -p /usr/codecc/tool_scan
COPY sdk /usr/codecc/tool_scan/sdk/
COPY third_rules /usr/codecc/tool_scan/third_rules/
COPY tool /usr/codecc/tool_scan/tool/
RUN chmod -R 755 /usr/codecc/tool_scan
WORKDIR /usr/codecc/tool_scan